# Generated by Django 5.1.5 on 2025-01-14 20:03

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$')])),
                ('username', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')])),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9!@#$%^&*()_+]*$')])),
                ('confirmpassword', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9!@#$%^&*()_+]*$')])),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
