# Generated by Django 5.1.5 on 2025-01-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('nombreheroe', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=20)),
            ],
        ),
    ]
