# Generated by Django 5.1.5 on 2025-01-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='power',
            field=models.CharField(max_length=100),
        ),
    ]
